---
# Authoritative Server (AS) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: as-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as
  template:
    metadata:
      labels:
        app: as
    spec:
      containers:
        - name: as
          image: mihirpenugonda/auth_server-as:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 53533
              protocol: UDP
---
# Authoritative Server (AS) Service
apiVersion: v1
kind: Service
metadata:
  name: as-service
spec:
  type: NodePort
  selector:
    app: as
  ports:
    - port: 53533
      targetPort: 53533
      nodePort: 30001
      protocol: UDP
---
# Fibonacci Server (FS) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs
  template:
    metadata:
      labels:
        app: fs
    spec:
      containers:
        - name: fs
          image: mihirpenugonda/auth_server-fs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
---
# Fibonacci Server (FS) Service
apiVersion: v1
kind: Service
metadata:
  name: fs-service
spec:
  type: NodePort
  selector:
    app: fs
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30002
---
# User Server (US) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us
  template:
    metadata:
      labels:
        app: us
    spec:
      containers:
        - name: us
          image: mihirpenugonda/auth_server-us:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
# User Server (US) Service
apiVersion: v1
kind: Service
metadata:
  name: us-service
spec:
  type: NodePort
  selector:
    app: us
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003
