version: "3"

services:
  as:
    build: ./AS
    ports:
      - "53533:53533/udp"
    volumes:
      - as-data:/tmp
    networks:
      - dns_network

  fs:
    build: ./FS
    ports:
      - "9090:9090"
    depends_on:
      - as
    networks:
      - dns_network
    environment:
      - FIBONACCI_HOSTNAME=fibonacci.com
      - FIBONACCI_IP=fs
      - AS_IP=as
      - AS_PORT=53533

  us:
    build: ./US
    ports:
      - "8081:8080"
    environment:
      - FLASK_APP=user_server.py
      - AS_IP=as
    depends_on:
      - as
      - fs
    networks:
      - dns_network

networks:
  dns_network:
    driver: bridge

volumes:
  as-data:
